# Generated by Django 4.2.1 on 2023-10-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_chat', '0002_chatsession_title_alter_chatsession_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
