# Generated by Django 4.2.1 on 2023-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_accounts', '0002_customuser_comments_made_customuser_question_asked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teleporter',
            field=models.TextField(default='The teleporter is empty'),
        ),
    ]
