# Generated by Django 4.2.1 on 2023-09-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='question',
            field=models.TextField(default='sample_question'),
        ),
    ]
