# Generated by Django 4.2.1 on 2023-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0002_usercomment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='correctness',
            field=models.CharField(choices=[('correct', 'correct'), ('incorrect', 'incorrect'), ('partial_correct', 'partial_correct'), ('not_classified', 'not_classified')], default='not_classified', max_length=15),
        ),
    ]
