# Generated by Django 4.2.1 on 2023-09-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0003_usercomment_correctness'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='modelType',
            field=models.CharField(default='GPT3.5', max_length=20),
        ),
    ]
