# Generated by Django 4.2.1 on 2023-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0004_usercomment_modeltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='username',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='user_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
