# Generated by Django 4.2.1 on 2023-10-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quantum_app', '0005_remove_usercomment_username_usercomment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='followup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='correctness',
            field=models.CharField(choices=[('correct', 'correct'), ('incorrect', 'incorrect'), ('partial_correct', 'partial_correct'), ('not_classified', 'not_classified'), ('doubts', 'doubts')], default='not_classified', max_length=15),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discussion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quantum_app.usercomment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
