# Generated by Django 4.2.1 on 2023-10-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0006_usercomment_followup_alter_usercomment_correctness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_c',
            old_name='user_id',
            new_name='user',
        ),
    ]
