# Generated by Django 4.2.1 on 2023-10-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum_app', '0007_rename_user_id_comment_c_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
